name = "aconf"
grammar = "aconf"
path_suffixes = ["aconf",]
line_comments = ["//"]
block_comments = ["/*", "*/"]
file_extensions = ["aconf"]
autoclose_before = ",]}"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment", "string"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["comment", "string"] },
]
