id = "aconf-zed-extension"
name = "Aconf"
version = "0.1.0"
schema_version = 1
authors = ["LuTheCoder <luthecoder@gmail.com>"]
description = "Aconf language support for Zed Editor"
repository = "https://github.com/Lu-TheCoder/zed-aconf"

[grammars.aconf]
repository = "https://github.com/Lu-TheCoder/tree-sitter-aconf"
commit = "1fe5b1fe2c0740466e20c245ebc3ebdbb6ece470"
file_extensions = ["aconf"]
